import 'package:the_exchange_app/models/currencies.dart';

List<CountryCurrency> kCountriesCurrenciesList = [
  CountryCurrency(
    countryISOCode: "ca",
    countryName: "Canada",
    currencyISOCode: "cad",
    currencyName: "Canadian Dollar",
    region: "Main",
    isChecked: false,
    firstItem: true,
  ),
  CountryCurrency(
    countryISOCode: "eu",
    countryName: "Europe",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Main",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gb",
    countryName: "United Kingdom",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Main",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "us",
    countryName: "United States",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Main",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ar",
    countryName: "Argentina",
    currencyISOCode: "ars",
    currencyName: "Argentine Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: true,
  ),
  CountryCurrency(
    countryISOCode: "bo",
    countryName: "Bolivia",
    currencyISOCode: "bob",
    currencyName: "Boliviano",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "br",
    countryName: "Brazil",
    currencyISOCode: "brl",
    currencyName: "Brazilian Real",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cl",
    countryName: "Chile",
    currencyISOCode: "clp",
    currencyName: "Chilean Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "co",
    countryName: "Colombia",
    currencyISOCode: "cop",
    currencyName: "Colombian Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cr",
    countryName: "Costa Rica",
    currencyISOCode: "crc",
    currencyName: "Costa Rican Colon",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cu",
    countryName: "Cuba",
    currencyISOCode: "cup",
    currencyName: "Cuban Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "do",
    countryName: "Dominican Republic",
    currencyISOCode: "dop",
    currencyName: "Dominican Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ec",
    countryName: "Ecuador",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sv",
    countryName: "El Salvador",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gt",
    countryName: "Guatemala",
    currencyISOCode: "gtq",
    currencyName: "Quetzal",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "hn",
    countryName: "Honduras",
    currencyISOCode: "hnl",
    currencyName: "Lempira",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mx",
    countryName: "Mexico",
    currencyISOCode: "mxn",
    currencyName: "Mexican Peso",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ni",
    countryName: "Nicaragua",
    currencyISOCode: "nio",
    currencyName: "Cordoba Oro",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pa",
    countryName: "Panama",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "py",
    countryName: "Paraguay",
    currencyISOCode: "pyg",
    currencyName: "Guarani",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pe",
    countryName: "Peru",
    currencyISOCode: "pen",
    currencyName: "Sol",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pr",
    countryName: "Puerto Rico",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "uy",
    countryName: "Uruguay",
    currencyISOCode: "uyu",
    currencyName: "Peso Uruguayo",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ve",
    countryName: "Venezuela",
    currencyISOCode: "ves",
    currencyName: "Bolívar",
    region: "Latin America",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "ai",
      countryName: "Anguilla",
      currencyISOCode: "xcd",
      currencyName: "East Caribbean Dollar",
      region: "Caribbean",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "ag",
    countryName: "Antigua and Barbuda",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "aw",
    countryName: "Aruba",
    currencyISOCode: "awg",
    currencyName: "Aruban Florin",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bs",
    countryName: "Bahamas",
    currencyISOCode: "bsd",
    currencyName: "Bahamian Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bb",
    countryName: "Barbados",
    currencyISOCode: "bbd",
    currencyName: "Barbados Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bz",
    countryName: "Belize",
    currencyISOCode: "bzd",
    currencyName: "Belize Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bm",
    countryName: "Bermuda",
    currencyISOCode: "bmd",
    currencyName: "Bermudian Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bq",
    countryName: "Bonaire, Sint Eustatius and Saba",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ky",
    countryName: "Cayman Islands",
    currencyISOCode: "kyd",
    currencyName: "Cayman Islands Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cw",
    countryName: "Curaçao",
    currencyISOCode: "ang",
    currencyName: "Netherlands Antillean Guilder",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "dm",
    countryName: "Dominica",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gf",
    countryName: "French Guiana",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gd",
    countryName: "Grenada",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gp",
    countryName: "Guadeloupe",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gy",
    countryName: "Guyana",
    currencyISOCode: "gyd",
    currencyName: "Guyana Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ht",
    countryName: "Haiti",
    currencyISOCode: "htg",
    currencyName: "Gourde",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "jm",
    countryName: "Jamaica",
    currencyISOCode: "jmd",
    currencyName: "Jamaican Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mq",
    countryName: "Martinique",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ms",
    countryName: "Montserrat",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bl",
    countryName: "Saint Barthélemy",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kn",
    countryName: "Saint Kitts &amp; Nevis",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lc",
    countryName: "Saint Lucia",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mf",
    countryName: "Saint Martin",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "vc",
    countryName: "Saint Vincent and the Grenadines",
    currencyISOCode: "xcd",
    currencyName: "East Caribbean Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sx",
    countryName: "Sint Maarten",
    currencyISOCode: "ang",
    currencyName: "Netherlands Antillean Guilder",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sr",
    countryName: "Suriname",
    currencyISOCode: "srd",
    currencyName: "Surinam Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tt",
    countryName: "Trinidad and Tobago",
    currencyISOCode: "ttd",
    currencyName: "Trinidad and Tobago Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tc",
    countryName: "Turks and Caicos Islands",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "vg",
    countryName: "Virgin Islands, British",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "vi",
    countryName: "Virgin Islands, U.S.",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Caribbean",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "ax",
      countryName: "Aland Islands",
      currencyISOCode: "eur",
      currencyName: "Euro",
      region: "Europe",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "al",
    countryName: "Albania",
    currencyISOCode: "all",
    currencyName: "Lek",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ad",
    countryName: "Andorra",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "am",
    countryName: "Armenia",
    currencyISOCode: "amd",
    currencyName: "Armenian Dram",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "at",
    countryName: "Austria",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "by",
    countryName: "Belarus",
    currencyISOCode: "byn",
    currencyName: "Belarusian Ruble",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "be",
    countryName: "Belgium",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ba",
    countryName: "Bosnia and Herzegovina",
    currencyISOCode: "bam",
    currencyName: "Convertible Mark",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bv",
    countryName: "Bouvet Island",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bg",
    countryName: "Bulgaria",
    currencyISOCode: "bgn",
    currencyName: "Bulgarian Lev",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "hr",
    countryName: "Croatia",
    currencyISOCode: "hrk",
    currencyName: "Kuna",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cy",
    countryName: "Cyprus",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cz",
    countryName: "Czechia",
    currencyISOCode: "czk",
    currencyName: "Czech Koruna",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "dk",
    countryName: "Denmark",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ee",
    countryName: "Estonia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "fo",
    countryName: "Faroe Islands",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "fi",
    countryName: "Finland",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "fr",
    countryName: "France",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ge",
    countryName: "Georgia",
    currencyISOCode: "gel",
    currencyName: "Lari",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "de",
    countryName: "Germany",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gr",
    countryName: "Greece",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gl",
    countryName: "Greenland",
    currencyISOCode: "dkk",
    currencyName: "Danish Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gg",
    countryName: "Guernsey",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "hu",
    countryName: "Hungary",
    currencyISOCode: "huf",
    currencyName: "Forint",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "is",
    countryName: "Iceland",
    currencyISOCode: "isk",
    currencyName: "Iceland Krona",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ie",
    countryName: "Ireland",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "im",
    countryName: "Isle of Man",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "it",
    countryName: "Italy",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "je",
    countryName: "Jersey",
    currencyISOCode: "gbp",
    currencyName: "Pound Sterling",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lv",
    countryName: "Latvia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "li",
    countryName: "Liechtenstein",
    currencyISOCode: "chf",
    currencyName: "Swiss Franc",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lt",
    countryName: "Lithuania",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lu",
    countryName: "Luxembourg",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mg",
    countryName: "Madagascar",
    currencyISOCode: "mga",
    currencyName: "Malagasy Ariary",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mt",
    countryName: "Malta",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "md",
    countryName: "Moldova",
    currencyISOCode: "mdl",
    currencyName: "Moldovan Leu",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mc",
    countryName: "Monaco",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "me",
    countryName: "Montenegro",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nl",
    countryName: "Netherlands",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mk",
    countryName: "North Macedonia",
    currencyISOCode: "mkd",
    currencyName: "Denar",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "no",
    countryName: "Norway",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pl",
    countryName: "Poland",
    currencyISOCode: "pln",
    currencyName: "Zloty",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pt",
    countryName: "Portugal",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ro",
    countryName: "Romania",
    currencyISOCode: "ron",
    currencyName: "Romanian Leu",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ru",
    countryName: "Russia",
    currencyISOCode: "rub",
    currencyName: "Russian Ruble",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pm",
    countryName: "Saint Pierre and Miquelon",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sm",
    countryName: "San Marino",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "rs",
    countryName: "Serbia",
    currencyISOCode: "rsd",
    currencyName: "Serbian Dinar",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sk",
    countryName: "Slovakia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "si",
    countryName: "Slovenia",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "es",
    countryName: "Spain",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sj",
    countryName: "Svalbard and Jan Mayen",
    currencyISOCode: "nok",
    currencyName: "Norwegian Krone",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "se",
    countryName: "Sweden",
    currencyISOCode: "sek",
    currencyName: "Swedish Krona",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ch",
    countryName: "Switzerland",
    currencyISOCode: "chf",
    currencyName: "Swiss Franc",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ua",
    countryName: "Ukraine",
    currencyISOCode: "uah",
    currencyName: "Hryvnia",
    region: "Europe",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "af",
      countryName: "Afghanistan",
      currencyISOCode: "afn",
      currencyName: "Afghani",
      region: "Middle East",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "bh",
    countryName: "Bahrain",
    currencyISOCode: "bhd",
    currencyName: "Bahraini Dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ir",
    countryName: "Iran",
    currencyISOCode: "irr",
    currencyName: "Iranian Rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "iq",
    countryName: "Iraq",
    currencyISOCode: "iqd",
    currencyName: "Iraqi Dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "il",
    countryName: "Israel",
    currencyISOCode: "ils",
    currencyName: "New Israeli Sheqel",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "jo",
    countryName: "Jordan",
    currencyISOCode: "jod",
    currencyName: "Jordanian Dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kw",
    countryName: "Kuwait",
    currencyISOCode: "kwd",
    currencyName: "Kuwaiti Dinar",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lb",
    countryName: "Lebanon",
    currencyISOCode: "lbp",
    currencyName: "Lebanese Pound",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "om",
    countryName: "Oman",
    currencyISOCode: "omr",
    currencyName: "Rial Omani",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pk",
    countryName: "Pakistan",
    currencyISOCode: "pkr",
    currencyName: "Pakistan Rupee",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "qa",
    countryName: "Qatar",
    currencyISOCode: "qar",
    currencyName: "Qatari Rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sa",
    countryName: "Saudi Arabia",
    currencyISOCode: "sar",
    currencyName: "Saudi Riyal",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ae",
    countryName: "United Arab Emirates",
    currencyISOCode: "aed",
    currencyName: "UAE Dirham",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ye",
    countryName: "Yemen",
    currencyISOCode: "yer",
    currencyName: "Yemeni Rial",
    region: "Middle East",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "az",
      countryName: "Azerbaijan",
      currencyISOCode: "azn",
      currencyName: "Azerbaijan Manat",
      region: "Asia",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "bd",
    countryName: "Bangladesh",
    currencyISOCode: "bdt",
    currencyName: "Taka",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bt",
    countryName: "Bhutan",
    currencyISOCode: "btn",
    currencyName: "Ngultrum",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "io",
    countryName: "British Indian Ocean Territory",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bn",
    countryName: "Brunei Darussalam",
    currencyISOCode: "bnd",
    currencyName: "Brunei Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kh",
    countryName: "Cambodia",
    currencyISOCode: "khr",
    currencyName: "Riel",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cn",
    countryName: "China",
    currencyISOCode: "cny",
    currencyName: "Yuan Renminbi",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "hk",
    countryName: "Hong Kong",
    currencyISOCode: "hkd",
    currencyName: "Hong Kong Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "in",
    countryName: "India",
    currencyISOCode: "inr",
    currencyName: "Indian Rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "id",
    countryName: "Indonesia",
    currencyISOCode: "idr",
    currencyName: "Rupiah",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "jp",
    countryName: "Japan",
    currencyISOCode: "jpy",
    currencyName: "Yen",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kz",
    countryName: "Kazakstan",
    currencyISOCode: "kzt",
    currencyName: "Tenge",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kr",
    countryName: "Korea",
    currencyISOCode: "krw",
    currencyName: "Won",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "kg",
    countryName: "Kyrgyzstan",
    currencyISOCode: "kgs",
    currencyName: "Som",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "la",
    countryName: "Laos",
    currencyISOCode: "lak",
    currencyName: "Lao Kip",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mo",
    countryName: "Macao",
    currencyISOCode: "mop",
    currencyName: "Pataca",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "my",
    countryName: "Malaysia",
    currencyISOCode: "myr",
    currencyName: "Malaysian Ringgit",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mv",
    countryName: "Maldives",
    currencyISOCode: "mvr",
    currencyName: "Rufiyaa",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mm",
    countryName: "Myanmar",
    currencyISOCode: "mmk",
    currencyName: "Kyat",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "np",
    countryName: "Nepal",
    currencyISOCode: "npr",
    currencyName: "Nepalese Rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ph",
    countryName: "Philippines",
    currencyISOCode: "php",
    currencyName: "Philippine Peso",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sg",
    countryName: "Singapore",
    currencyISOCode: "sgd",
    currencyName: "Singapore Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lk",
    countryName: "Sri Lanka",
    currencyISOCode: "lkr",
    currencyName: "Sri Lanka Rupee",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tw",
    countryName: "Taiwan",
    currencyISOCode: "twd",
    currencyName: "New Taiwan Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tj",
    countryName: "Tajikistan",
    currencyISOCode: "tjs",
    currencyName: "Somoni",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "th",
    countryName: "Thailand",
    currencyISOCode: "thb",
    currencyName: "Baht",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tl",
    countryName: "Timor-Leste",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tr",
    countryName: "Turkey",
    currencyISOCode: "try",
    currencyName: "Turkish Lira",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tm",
    countryName: "Turkmenistan",
    currencyISOCode: "tmt",
    currencyName: "Turkmenistan New Manat",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "uz",
    countryName: "Uzbekistan",
    currencyISOCode: "uzs",
    currencyName: "Uzbekistan Sum",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "vn",
    countryName: "Vietnam",
    currencyISOCode: "vnd",
    currencyName: "Dong",
    region: "Asia",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "dz",
      countryName: "Algeria",
      currencyISOCode: "dzd",
      currencyName: "Algerian Dinar",
      region: "Africa",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "ao",
    countryName: "Angola",
    currencyISOCode: "aoa",
    currencyName: "Kwanza",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bj",
    countryName: "Benin",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bw",
    countryName: "Botswana",
    currencyISOCode: "bwp",
    currencyName: "Pula",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bf",
    countryName: "Burkina Faso",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "bi",
    countryName: "Burundi",
    currencyISOCode: "bif",
    currencyName: "Burundi Franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cm",
    countryName: "Cameroon",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cv",
    countryName: "Cape Verde",
    currencyISOCode: "cve",
    currencyName: "Cabo Verde Escudo",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cf",
    countryName: "Central African Republic",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "td",
    countryName: "Chad",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "km",
    countryName: "Comoros",
    currencyISOCode: "kmf",
    currencyName: "Comorian Franc ",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cg",
    countryName: "Congo",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cd",
    countryName: "Congo (DR)",
    currencyISOCode: "cdf",
    currencyName: "Congolese Franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ci",
    countryName: "Cote d&apos;Ivoire",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "dj",
    countryName: "Djibouti",
    currencyISOCode: "djf",
    currencyName: "Djibouti Franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "eg",
    countryName: "Egypt",
    currencyISOCode: "egp",
    currencyName: "Egyptian Pound",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gq",
    countryName: "Equatorial Guinea",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sz",
    countryName: "Eswatini",
    currencyISOCode: "szl",
    currencyName: "Lilangeni",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "et",
    countryName: "Ethiopia",
    currencyISOCode: "etb",
    currencyName: "Ethiopian Birr",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tf",
    countryName: "French Southern Territories",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ga",
    countryName: "Gabon",
    currencyISOCode: "xaf",
    currencyName: "Central African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gm",
    countryName: "Gambia",
    currencyISOCode: "gmd",
    currencyName: "Dalasi",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gh",
    countryName: "Ghana",
    currencyISOCode: "ghs",
    currencyName: "Ghana Cedi",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gn",
    countryName: "Guinea",
    currencyISOCode: "gnf",
    currencyName: "Guinean Franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gw",
    countryName: "Guinea-Bissau",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ke",
    countryName: "Kenya",
    currencyISOCode: "kes",
    currencyName: "Kenyan Shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ls",
    countryName: "Lesotho",
    currencyISOCode: "lsl",
    currencyName: "Loti",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "lr",
    countryName: "Liberia",
    currencyISOCode: "lrd",
    currencyName: "Liberian Dollar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ly",
    countryName: "Libya",
    currencyISOCode: "lyd",
    currencyName: "Libyan Dinar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mw",
    countryName: "Malawi",
    currencyISOCode: "mwk",
    currencyName: "Malawi Kwacha",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ml",
    countryName: "Mali",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mr",
    countryName: "Mauritania",
    currencyISOCode: "mru",
    currencyName: "Ouguiya",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mu",
    countryName: "Mauritius",
    currencyISOCode: "mur",
    currencyName: "Mauritius Rupee",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "yt",
    countryName: "Mayotte",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ma",
    countryName: "Morocco",
    currencyISOCode: "mad",
    currencyName: "Moroccan Dirham",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mz",
    countryName: "Mozambique",
    currencyISOCode: "mzn",
    currencyName: "Mozambique Metical",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "na",
    countryName: "Namibia",
    currencyISOCode: "nad",
    currencyName: "Namibia Dollar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ne",
    countryName: "Niger",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ng",
    countryName: "Nigeria",
    currencyISOCode: "ngn",
    currencyName: "Naira",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "re",
    countryName: "Reunion",
    currencyISOCode: "eur",
    currencyName: "Euro",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "rw",
    countryName: "Rwanda",
    currencyISOCode: "rwf",
    currencyName: "Rwanda Franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sn",
    countryName: "Senegal",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sc",
    countryName: "Seychelles",
    currencyISOCode: "scr",
    currencyName: "Seychelles Rupee",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sl",
    countryName: "Sierra Leone",
    currencyISOCode: "sll",
    currencyName: "Leone",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "so",
    countryName: "Somalia",
    currencyISOCode: "sos",
    currencyName: "Somali Shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "za",
    countryName: "South Africa",
    currencyISOCode: "zar",
    currencyName: "Rand",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sd",
    countryName: "Sudan",
    currencyISOCode: "sdg",
    currencyName: "Sudanese Pound",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tz",
    countryName: "Tanzania",
    currencyISOCode: "tzs",
    currencyName: "Tanzanian Shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tg",
    countryName: "Togo",
    currencyISOCode: "xof",
    currencyName: "West African CFA franc",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tn",
    countryName: "Tunisia",
    currencyISOCode: "tnd",
    currencyName: "Tunisian Dinar",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ug",
    countryName: "Uganda",
    currencyISOCode: "ugx",
    currencyName: "Uganda Shilling",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "eh",
    countryName: "Western Sahara",
    currencyISOCode: "mad",
    currencyName: "Moroccan Dirham",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "zm",
    countryName: "Zambia",
    currencyISOCode: "zmw",
    currencyName: "Zambian Kwacha",
    region: "Africa",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
      countryISOCode: "as",
      countryName: "American Samoa",
      currencyISOCode: "usd",
      currencyName: "US Dollar",
      region: "Oceania",
      isChecked: false,
      firstItem: true),
  CountryCurrency(
    countryISOCode: "au",
    countryName: "Australia",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cx",
    countryName: "Christmas Island",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "cc",
    countryName: "Cocos (Keeling) Islands",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ck",
    countryName: "Cook Islands",
    currencyISOCode: "nzd",
    currencyName: "New Zealand Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "fj",
    countryName: "Fiji",
    currencyISOCode: "fjd",
    currencyName: "Fiji Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pf",
    countryName: "French Polynesia",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "gu",
    countryName: "Guam",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "hm",
    countryName: "Heard and Mc Donald Islands",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "ki",
    countryName: "Kiribati",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mh",
    countryName: "Marshall Islands",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "fm",
    countryName: "Micronesia",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nr",
    countryName: "Nauru",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nc",
    countryName: "New Caledonia",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nz",
    countryName: "New Zealand",
    currencyISOCode: "nzd",
    currencyName: "New Zealand Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nu",
    countryName: "Niue",
    currencyISOCode: "nzd",
    currencyName: "New Zealand Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "nf",
    countryName: "Norfolk Island",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "mp",
    countryName: "Northern Mariana Islands",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pw",
    countryName: "Palau",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pg",
    countryName: "Papua New Guinea",
    currencyISOCode: "pgk",
    currencyName: "Kina",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "pn",
    countryName: "Pitcairn",
    currencyISOCode: "nzd",
    currencyName: "New Zealand Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "sb",
    countryName: "Solomon Islands",
    currencyISOCode: "sbd",
    currencyName: "Solomon Islands Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tk",
    countryName: "Tokelau",
    currencyISOCode: "nzd",
    currencyName: "New Zealand Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "to",
    countryName: "Tonga",
    currencyISOCode: "top",
    currencyName: "Pa’anga",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "tv",
    countryName: "Tuvalu",
    currencyISOCode: "aud",
    currencyName: "Australian Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "um",
    countryName: "United States Minor Outlying Islands",
    currencyISOCode: "usd",
    currencyName: "US Dollar",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  ),
  CountryCurrency(
    countryISOCode: "wf",
    countryName: "Wallis and Futuna",
    currencyISOCode: "xpf",
    currencyName: "CFP Franc",
    region: "Oceania",
    isChecked: false,
    firstItem: false,
  )
];
